menu:
- {name: 'Home', url: ''}
- {name: 'Portfolio', url: '/portfolio'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

about:
- {name: 'Conner Griffin', title: 'Doctoral Student', department: 'Mathematics', institution: 'University of Memphis', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'cgrffn11 at memphis dot edu', office: 'Dunn Hall 143', image: 'assets/img/cgrffn11.JPG', url: 'graduate-student'}

courses:
- {name: 'MATH 1910: Calculus I', url: 'calculus-I'}
- {name: 'MATH 2110: Calculus III', url: 'calculus-III'}

social:
- {icon: 'github', link: 'https://github.com/connergriffin'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/conner-griffin-6ba3a9218'}
- {icon: 'twitter', link: 'https://twitter.com/coffergrinnin'}
- {icon: 'instagram', link: 'https://instagram.com/connersgriffin'}

contacts:
- {name: 'Conner Griffin', title: 'Doctoral Student', department: 'Mathematics', institution: 'University of Memphis', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'cgrffn11 at memphis dot edu', office: 'Dunn Hall 312', image: 'assets/img/cgrffn11.JPG'}
