menu:
- {name: 'Home', url: ''}
- {name: 'Portfolio', url: '/portfolio'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

about:
- {name: 'Conner Griffin', title: 'Ross Visiting Assistant Professor', department: 'Mathematics', institution: 'Ohio State University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'griffin dot 1101 at osu dot edu', office: 'Mathematics Tower 748', image: 'assets/img/Griffin_08_15_24.jpg'}

courses:
- {name: 'MATH 1910: Calculus I', url: 'calculus-I'}
- {name: 'MATH 2110: Calculus III', url: 'calculus-III'}

social:
- {icon: 'github', link: 'https://github.com/connergriffin'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/conner-griffin-6ba3a9218'}

contacts:
- {name: 'Conner Griffin', title: 'Ross Visiting Assistant Professor', department: 'Mathematics', institution: 'Ohio State University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'griffin dot 1101 at osu dot edu', office: 'Mathematics Tower 748', image: 'assets/img/Griffin_08_15_24.jpg'}
